### ISSUE TITLE
Where is baddest.dat created?

### ISSUE THREAD

**Issue by ryanfantus** [SnakeManPMC/linux-baddest-batches#1]
Hi, I've been trying to implement this in my own BBS but all of the binaries fail at trying to open baddest.dat. I created an empty file baddest.dat but they still fail (presumably because we're trying to use fopen on that file as a binary file).

My question is, where is this file created? I can't figure this out anywhere :)

**Comment by SnakeManPMC** [comment]
Oh wow this is blast from the past, the good old scene BBS era, really cool to see someone still doing stuff there :)

The datafile is called "baddest.dat" and its hardcoded to "/home/bbs/pmc/" directory.

https://github.com/SnakeManPMC/linux-baddest-batches/blob/master/baddest.c#L143

Cant remember that far back, I mean this was initially coded back in the frigging 1990's heh, but just gut feeling right now is that such directory and even file name should be in some config file instead of hardcoded into the .C source code.

Besides that home dir, its also hardcoded to /eggdrop/ to look for eggdrop IRC bot files there. Again, very much hardcoded to my own system which should be done with config file instead.

**Comment by ryanfantus** [comment]
Thanks! Yeah, I'm trying to get all these daydream doors that you wrote working as I still use dd myself :)
